/**
 Name: Connected World
 File Name: CW.env
 Date: 04/27/2018
 Ver. 0.05
 Last Update: Bart
 */

 export const environment = {
    production: false,
      //mapboxKey : 'pk.eyJ1Ijoic3Qtc2F0aGlzaCIsImEiOiJjajQzeWMyM3cwMzZwMndyeWFvcXRsNXdkIn0.ptibfHT7Fo7GQqWtArxWSw',
      mapboxKey : 'pk.eyJ1IjoiZW1pbWx1bWluYSIsImEiOiJjaWpiYmpnbnYwMGJydWxtNGpxYW1ud2hiIn0.GTH60dU0ViJo84t0wdClhA',
      apiUrl:   'http://localhost:8080',
      fileStorage:  'http://localhost:8080',
      buildingManagerSubscription: 2,
      buildingIntelligenceSubscription: 3,
      blmSubscription: 4,
      broadband: 7,
      wifi: 8,
      das: 9,
      voip: 10,
      frame: 13,
      atm: 14,
      NOT_CONNECTED: { id: 3, text: 'Not Connected'},
      NEARNET: { id: 6, text: 'Near Net'},
      ONNET_ID: 1,
      ONNET_LIMITED_ACCESS_ID: 5,
      CONNECTED_ID: 1,
      INPROGRESS_ID: 2,
      OFFNET_ID: 2,
      enterpriseProfilerUrl: 'http://localhost:8084',
      //enterpriseProfilerUrl: 'https://stageep.connectbase.com',
      unitMBInBytes: 1048576,
      PORTAL_USER : 9,
      BUSINESS_PARTNER_ID : 10,
      EDIT_USER : 2,
      VIEW_USER : 3,
  
      buildingIconPath: '/assets/images/mapicon/building/icon/',
      locationIconPath: '/assets/images/mapicon/location/icon/',
      defaultViewZoom: 16,
  
      defaultRouteColor: '#0E30EE',
      defaultRouteStatus: {id: 1, text: "Active"},
      defaultCountry: { id: 223, text: 'United States', code: 'USA', code2: 'US' },
      maxUploadSize: 100,
  
      authToken: '74465ef431914903a273aac94db45107',
      authenticationApiUrl: 'https://stagecwapi.connected2fiber.com/authentication_stage',
      applicationVersion: '3.7.0',
      uniProductId: 15,
      nniProductId: 17,
      applicationTitle: 'Connected World',
      application: 'CW',
      nodeApiUrl: "http://localhost:8083",
      //For connect UAT DB
      // nodeApiUrl: 'https://uat-v2-api.connected2fiber.com',
      mapboxStaticImageUrl: 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/',
      mapboxGeocodeUrl: 'https://api.mapbox.com/geocoding/v5/mapbox.places/',
      networkFinderURL: 'http://nf.connected2fiber.com',
      epUrl: 'https://stage-ep.connected2fiber.com',
      NW_STATUS_PROSPECT: 5,
      cpqApiUrl:'"https://uatcw.connected2fiber.com',
      cwApiUrl: "http://localhost:8080",
      // url pointer but in this case this should be pointing internally. EP depends on this value.
      cwUrl: "",
      // ip address for staging/uat offnetPricingApi
      offnetPricingApi: "http://192.168.97.8:8085/api/v2/internal/remotePrice",
      mapboxTilesetApi: 'https://api.mapbox.com/v4/',
      routeBufferZoom: 15,
      routeBufferMaxDistance: 5000,
      defaultUserPassword: "Admin@123",
  
      offnetInternalPricingApi: "https://uat-pricing.connected2fiber.com/api/v2/internal/remotePrice",
      apiPricingUrl: "http://localhost:9098",
      inlineManualUrl:"",
      cbm:"",
      oktaHostURL: "https://capestartconnected2fiber.okta.com",
      oktaToken: '006ACNS1Pl9fDI7jTJNzM9mdtSoxv1kwzFf5kRJU4y',
      oktaIssuer: "https://capestartconnected2fiber.okta.com/oauth2/aus3vhpfgtZA88gpY5d6",
      oktaClientId: '0oa3nj4faXzSSdcyH5d6',
      cpqRulesEngine: true,
      showVzSSO:false,
      oktaSSO: false,
      oktaClientSecret: "Xb66efrIhht4nmePA7gSqvEkERbOMSDQ9N_oAVdz",
      oktaRedirectURL: "http://localhost:4200",
      BUILDING_CONNECTION_STATUS_PROSPECT:7,
      internalPricingCustomer: 1,
      externalPricingCustomer: 2,
      socketUrl: 'https://uatcw.connected2fiber.com',
      vzCanvasCookieMatch: "vz",
      oktaCallBackUrl: "https://uatcw.connected2fiber.com/#/okta-callback",
      oktaSSOGroupId: "00g2b1sq34vPxwN645d7",
      orderingAPI:"http://localhost",
      apiRouterURL:"http://localhost",
      COMPOSER_URL: "https://logi.connectbase.com:8443/composer",
      ADMIN: 1,
      BILLING_ADMIN: 7,
      ROLE_CARRIER_RELATIONS_ADMIN: 8 ,
      LOGI_DEFAULT_DASHBOARD:"61bcab9c3b28821608853e9e",
      LIST_MANAGER_PERMISSION: 18,
      DEFAULT_FORMAT_TYPE: 1,
      OBSOLETE_FORMAT_TYPE: 2,
      CENSUS_FORMAT_TYPE: 3,
      maxWaitTime:2000,
      BUSINESS_PARTNER:10,
      forceFetch:'',
      FILE_SERVER_IMAGE_URL:'',
      SSO_ONLY_DOMAINS:['test.comm'],
      LOGI_DASHBOARD_BUSINESS_INTELLIGENCE:['one'],
      LOGI_DASHBOARD_BUSINESS_ANALYTICS:['one'],
      LOGI_DASHBOARD_MONITOR_AND_DESIGN:['one'],
      CENSUS_POLYGON_FORMAT_TYPE: 4,
      CENSUS_TABULAR_FORMAT_TYPE:3,
      CENSUS_PLOYGON_SUB_FORMAT_TYPE: 5,
      oktaPingIdpId:'',
      geoMapboxKey:'',
      geoMapRateLimitCount:3,
    layerPermissionId: 22,
      LOGI_DASHBOARD_MARKET_INTELLIGENCE:[],
      mapboxUploadPrefix: 'emimlumina.',
      defaultLayerPermissionGroupId:2,
      searchViewZoom:15,
    NNA_BACKEND_URL: 'https://stage-nna.connectbase.com',
    role_view_user: 3,
    COOPERATE_USER: 11,
    CPQ_ALLOW_DUPLICATES_IN_ADDRESS_IMPORT_PERMISSION_ID: 1,
    BUILD_STATUS_PROSPECT: 7,
    impedimentMinZoom: 12,
    PLANNED_ID: 4,
    NNA_METERING: 'http://4.246.150.20:4000',
    dataCenterId:26,
    ALLOW_CPQ_PRICING_GRID_FIELDS_FEED_TO_CPQ_GRID_VIEW_PERMISSION_ID:30,
    ALLOW_CPQ_PRICING_GRID_FIELDS_FEED_TO_CPQ_GRID_CSV_EXPORT_PERMISSION_ID:31,
    ADVANCED_MARKET_EXPLORER_ID: 28,
    CPQ_ALLOW_DESIRED_FIELD: 27,
  };
  